### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by Norric1Admin** [open-sdg/sdg-build#30]
The table of [10.b.1](https://sustainabledevelopment-uk.github.io/10-b-1/) is in need of rounding, as certain years show multiple decimal places. A rounding fix went through on [0.3.2](https://github.com/open-sdg/sdg-build/releases/tag/0.3.2) but this didn't solve the problem.

**Comment by brockfanning** [comment]
Just a note that the rounding fix from 0.3.2 was related to the stats data (ie, the "Reporting Status" page in Open SDG).

I notice that these decimals seem to be present in the source CSV files. Is this behavior new?

The tricky part here is that some users may actually want their decimal places. So if we do any rounding of data then it would need to be optional and configurable. We would also want to consider whether any rounding could be done by the reporting platform (since it is just for humans anyway).

**Comment by dougmet** [comment]
Tricky this one. I think I agree that we should fix it on the front-end. Although one could make the same argument for reporting. The JSON and csv are also part of the data API and I feel they should be as raw as possible. So I think +1 for a front end fix.

**Comment by Norric1Admin** [comment]
Maybe the best option would be to have a front end limit to the number of decimal places allowed. If it goes above 3/4dp (for example), then the site caps it there. Could you suggest a good starting place?

**Comment by LucyGwilliamAdmin** [comment]
Also an issue in open-sdg [#199](https://github.com/open-sdg/open-sdg/issues/199)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning can this be closed now?

**Comment by brockfanning** [comment]
Yes, I think we can close this out.
