### ISSUE TITLE
Mix of SDMX structure/structureSpecific

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#44]
Is it possible for a mixture of SDMX-ML structure and SDMX-ML structureSpecific files to be uploaded to the same data repository?

**Comment by brockfanning** [comment]
Yes, that should be fine. The basic pattern for using that object-oriented approach is to create any number of "Inputs", and pass them as a list, into the desired "Output".

But you would need some way to tell them apart, like having them in different folders, because each file would need to loaded using the appropriate class (InputSdmxMl_Structure vs InputSdmxMl_StructureSpecific).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning the two different types of SDMX-ML files start differently:
StructureSpecific:
![image](https://user-images.githubusercontent.com/43404358/62872152-c4303500-bd14-11e9-8742-814cf610bcf4.png)
Structure:
![image](https://user-images.githubusercontent.com/43404358/62872183-d4481480-bd14-11e9-8717-3066f985225c.png)

Do you think it would be possible to differentiate between them using this e.g. 
if message==StructureSpecificData:
    use StructureSpecific class
else if message==GenericData:
    use Structure class

**Comment by brockfanning** [comment]
Yes, there could be a helper function that reads an XML file and then loads it again with the appropriate class based on what its root element is.

**Comment by LucyGwilliamAdmin** [comment]
Ok thanks, will take a look

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning 
I've been editing [this file](https://github.com/sdg-kyrgyzstan/open-sdg-data-starter/blob/sdmx/scripts/output.py) to test allowing a mix of files which seems to have worked. But then when I upload a file with the InputSdmxMl_Structure type I'm getting [this error](**https://circleci.com/gh/sdg-kyrgyzstan/open-sdg-data-starter/1705):
![image](https://user-images.githubusercontent.com/43404358/63511502-48cf4000-c4d9-11e9-86fa-ec7286db9008.png)

**Comment by LucyGwilliamAdmin** [comment]
This is how a Series starts within the file I uploaded?
I'm not entirely sure how this works so might be totally off, in this line of the code:
`return series.find(".//SeriesKey/Value[@id='SERIES']").attrib['value']`
should it be:
`return series.find(".//Series/SeriesKey/Value[@id='SERIES']").attrib['value']`

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning could you give me access to sdg-build on Circle please? Just so I can see if my branch is passing the tests?

**Comment by LucyGwilliamAdmin** [comment]
So I've managed to get past the above issue. But I have to change quite a lot of the file:

@brockfanning - do you know what might be causing this?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Sorry I haven't had a chance to look into this. Can you point me to the files and/or branches that I should be looking at?

**Comment by LucyGwilliamAdmin** [comment]
Sorry forgot to attach the file: https://github.com/open-sdg/sdg-build/compare/master...LucyGwilliamAdmin:sdmx-test7?expand=1

**Comment by LucyGwilliamAdmin** [comment]
And this is the error I'm getting now:
https://circleci.com/gh/sdg-kyrgyzstan/open-sdg-data-starter/1740
![image](https://user-images.githubusercontent.com/43404358/64169130-f4b34c80-ce44-11e9-8464-dd3ba3797822.png)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning Nevermind got it to pass now :)

**Comment by LucyGwilliamAdmin** [comment]
So I've managed to get all of Kyrgyzstan's SDMX files uploaded to a test branch so far, but I've had to make these changes to InputSdmxMl_Structure.py:
https://github.com/open-sdg/sdg-build/compare/master...LucyGwilliamAdmin:sdmx-test-8?expand=1 on my fork (if you're wondering why there's so many branches, they don't seem to be building when I just make a change)

Is there a way the script could be configurable in case different terms are used?

**Comment by brockfanning** [comment]
Nice, it looks like you're finding some places where SDMX tends to vary, even within a "format" like Structure or Structure Specific. I think we can surely leverage the object-oriented stuff to make things more configurable. But before diving into that - I just want to make sure that it's necessary.

I notice that a big difference is "concept" instead of "id", in the "Value" children of a "SeriesKey". Is there any chance that one or the other here is correct, and the other incorrect? If so, we should standardize around the correct one. We might run this past an SDMX guru, to be sure.

The other difference is a totally different way to get the year. I've got an idea on that, but it also depends on the answer to the "concept vs id" question.

Shot in the dark - I wonder if any of these differences are due to changes between SDMX 2.0 and SDMX 2.1?

**Comment by LucyGwilliamAdmin** [comment]
I was actually thinking something similar - surely something which is supposed to standardise data exchange would have different structure/terms across files.

I will contact Abdulla today and see if he knows why the differences occur.

**Comment by LucyGwilliamAdmin** [comment]
After speaking with Abdulla, and converting the problem files to the suggested type this isn't an issue anymore?

@brockfanning can we close?

**Comment by brockfanning** [comment]
Yep, I think so.
