### ISSUE TITLE
Having SDMX for output

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#52]
We now have a few ways to have SDMX as an input. I guess we want to start considering how we will export SDMX files from a platform.

I think we discussed before that it would be good to have the functionality to download SDMX-ML files and also to make the data available at a URL.

In the UK we were hoping that we could carrying on uploading CSVs as our data files and then these could still get exported as SDMX using a mapping.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning what are your thoughts on this?

**Comment by brockfanning** [comment]
Some general thoughts are:
1. In implementing this, we may discover new requirements in the internal structure for this library. For example, in the output we may need to distinguish between "dimensions" and "attributes", but right now our internal structure is has nothing that would indicate which columns are "dimensions" and which columns are "attributes". We could also consider, rather than changing our internal structure, having some sort of a mapping passed to the SDMX output class that conveys that info.
2. I strongly recommend that try our best to use an open-source library to produce the output. I wonder if something like [pandaSDMX](https://pandasdmx.readthedocs.io/en/stable/) would work for us here. If we find ourselves writing code that outputs SDMX, that would be a shame. Then perhaps once we're familiar with whatever library we use, we can refactor the SDMX inputs to also leverage it.

**Comment by khaeru** [comment]
Hi —I want to bring khaeru/sdmx#3 to your attention, which sets up the basic machinery to write XML from Python SDMX objects. See e.g. [here](https://github.com/khaeru/sdmx/pull/3/files#diff-07fc18766e5facc4a882a0dd711a5a4dR54) for the key parts of the code, or the tests in test_writer_xml: [here](https://github.com/khaeru/sdmx/pull/3/files#diff-16e9045ad67da8d63f081572970ddc50).

I'm planning to incrementally extend this code, but since the XML format is pretty extensive, it's a bit of a challenge to choose where to start. For my own applications, I'd want to write simple ConceptSchemes and Codelists, and then reuse them via the same library. But I'd appreciate to hear what the specific use-cases are in sdg-build. I've skimmed the linked issues.

In particular, it would really help development if you could provide (pointers to) example objects, code, etc. that show intended usage, i.e. which subset of the IM is needed.
This would help me expand the test suite.
(Contributed code as PRs would also be very welcome, of course :smile:)

**Comment by brockfanning** [comment]
Thanks for the links @khaeru, that's exciting to see this is a possibility. We're not yet ready to write SDMX, but I'm hopeful that in the next few weeks we could get there. So I'll be checking in again soon.

@LucyGwilliamAdmin Though we've been leaning towards not generating the SDMX in sdg-build, I'm bouncing some ideas around, and I think it would help me to write them out and get feedback. I'm imagining a script, say `update_dsd.py`, which countries could use to generate a DSD and a mapping of CSV columns to SDMX concepts. This script is intended to be run many times, to gradually generate the DSD and mapping, which are commited to the data repo. The workflow would be something like:
1. Country runs `update_dsd.py` the first time, and many CSV files are generated:
    * `dimensions.csv` which contains a mapping of all the dimensions in the global DSD, as well as all the disaggregation columns in the country's data. Importantly it contains a column called "CSV Disaggregation".
    * A corresponding CSV file for each one of these dimensions, containing all the SDMX codes from the global DSD, as well as all the disaggregation values from the country's data. Importantly it contains a column called "CSV Disaggregation Value". Example of these files would be `CL_SEX.csv`.
2. Country commits these files to their data repository.
3. Country looks in the files for any overlap between global dimensions/codes and the disaggregations/values in their data. For example, there will probably be a "Sex" disaggregation with "Female" and "Male" in the country's data. The country would notice the overlap with "CL_SEX" in the global DSD, and so they'd enter "Sex" under "CSV Disaggregation".
4. Country runs the script a second time. The script notices that there are now duplicates for "Sex", and the script instructs the country how to remove the duplicates.
5. Country removes the duplicates as instructed.
6. Country runs the script a third/fourth/fifth/etc time, looping back to step 3 until they have everything mapped to disaggregations/values in the CSV.
7. Finally, when everything is mapped, running the script a final time generates a customised DSD file, which the country also commits to the data repo.
8. At this point, in theory, we could use those mapping files and the DSD to automatically generate SDMX from the CSV data.

**Comment by brockfanning** [comment]
I think we can close this, as we now have a "light" version of SDMX output, assuming that the data is SDMX-compliant.
