### ISSUE TITLE
Get indicator series - indicator code mapping from DSD for SDMX

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-build#95]
Currently using SDMX as input requires a code mapping to be maintained but Abdulla has advised that this is not necessary

From Abdulla:
>The mapping information is contained in the DSD (attached), in the form of annotations. If you look up the CL_SERIES code list, you will see that under each code there are three annotations, e.g.:
>![dsd_eg](https://user-images.githubusercontent.com/43404358/73089382-023da180-3ece-11ea-809e-3201ad795fe9.png)
>As you can see, the annotation Indicator contains indicator numbers, such as 1.2.1 or 1.4.2.
 
>Note also that 1.5.1 above is a multi-purpose indicator, i.e. it is at the same time 1.5.1, 11.5.1, and 13.1.1. In this case, multiple Indicator annotations are added.
 
>Other annotations contain official SGD indicator codes (e.g. C0200303) and titles, which are often different from series titles.

**Comment by brockfanning** [comment]
We may actually already be doing this. See the default "indicator_id_xpath" [here](https://github.com/open-sdg/sdg-build/blob/master/sdg/inputs/InputSdmx.py#L18). I think that if the mapping is missing, it falls back to whatever it finds there. It could be worth investigating what happens if the mapping is not used. My total guess is that, assuming the "indicator_id_xpath" was set correctly, it would work fine in all cases except for the multi-purpose indicators. (We haven't added any special code for multi-purpose indicators, as far as I know.)

**Comment by LucyGwilliamAdmin** [comment]
Ok great - I'll take a look at what happens if mapping is removed. If this works, it might be good if we can make changes so that it works for multi-purpose indicators.

**Comment by LucyGwilliamAdmin** [comment]
I'm not really sure how to look into this as even when I just remove one series code from the mapping, the build fails

**Comment by LucyGwilliamAdmin** [comment]
Is there any chance you could take a quick look at this if you have time? Just think it would be good to have this sorted before we go to Kyrgyzstan next month as the code mapping will be one less thing for them to worry about.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin In order for the indicator to be automatically parsed, that `indicator_id_xpath` parameter needs to point to something in the XML files that has the indicator id. During the input, whenever the code needs to figure out an indicator's ID, it does this:
1. Look to see if anything is set in the `indicator_id_map`, and if so, use that.
2. Otherwise, look up the `indicator_id_xpath` and use it to drill down into the XML to find the indicator id.

The default `indicator_id_xpath` is `.//Annotation[AnnotationTitle='Indicator']/AnnotationText`. Right now in the Kyrgyzstan code, it is being set to `.//Name`. Of course, that `.//Name` is not really being used, I don't think, because you have an exhaustive `indicator_id_map`.

I just did a spot-check of 1-1-1.xml, and didn't see the indicator ID anywhere in the XML file. The automatic approach is not going to work unless the indicator ID can always be found at a predictable place in every series, so that place can be used as the `indicator_id_xpath`.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning thanks so much for the info.

I think that there would need to be functionality added so that rather than an indicator being found at a predictable place, a series code is found and then the series code is mapped to an indicator ID using the DSD.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I may be misunderstanding, but I think the challenge is knowing where in the DSD to look for the indicator ID. As far as I understand, the standard is now that `.//Annotation[AnnotationTitle='Indicator']//AnnotationText` location. But in some of Kyrgyzstan SDMX files that location does not exist. My suspicion is that you can either:
1. Continue using a hardcoded indicator ID map, or
2. Make sure that all the SDMX files are built using the latest structure (whatever it is that uses the location mentioned above)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning each SDMX file has a SERIES code for each Series e.g.
![image](https://user-images.githubusercontent.com/43404358/74179406-4b635480-4c35-11ea-86a5-80c3f8bd2bad.png)

and the DSD there is a SERIES code list which consists of all the SERIES codes, then it's within each Series section that `.//Annotation[AnnotationTitle='Indicator']//AnnotationText` is located e.g.
![image](https://user-images.githubusercontent.com/43404358/74179787-07248400-4c36-11ea-902d-3e091e463d68.png)

Sorry if I'm explaining something you already know, just trying to make sure we're talking about the same thing

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Thanks for that - sorry for my confusion before.

I put up a PR that seems to help get the build to run locally, at least. I haven't done any testing though. https://github.com/sdg-kyrgyzstan/open-sdg-data-starter/pull/234

* This updates to the latest sdg-build code
* This turns off the "git" functionality for the metadata input. That code is apparently still hardcoded to look for .csv files, so is causing problems. FYI this is what generates the automatic "last updated date" metadata.
* This removes the indicator_id_map, indicator_id_xpath, and indicator_name_xpath parameters, so that it can just rely on the defaults.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Also realized I had removed a couple of files during testing (the demo_indicator.csv and an English metadata file). I don't think that is necessary, and you can ignore that. Feel free to close my PR and try your own fix.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning think this is fixed now?

**Comment by brockfanning** [comment]
I think so, closing now.
